Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
        - Name: 选择ECS实例（Linux）
          Url: ros_templates/template-select-ecs.yaml
          PredefinedParameters: []
        - Name: 新建ECS实例
          Url: ros_templates/template-create-ecs.yaml
          PredefinedParameters: []
    TemplateConfigs:
      - Name: 选择ECS实例（Linux）
        Url: ros_templates/template-select-ecs.yaml
        PredefinedParameters: []
        DeployScene: ECS
      - Name: 新建ECS实例
        Url: ros_templates/template-create-ecs.yaml
        PredefinedParameters: []
        DeployScene: ECS
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      Prefix: Golang-
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      选择ECS实例（Linux）:
        EnablePrometheus: false
      新建ECS实例:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo.png
      Locale: zh-CN
      Name: Golang运行环境
      ShortDescription: Golang是一种静态类型、编译型的编程语言，由谷歌的Robert Griesemer、Rob Pike和Ken Thompson于2007年设计，并在2009年正式发布。Go语言设计的目标是实现高效的编译、高效的执行以及易于编程和高效的数据处理。
      Softwares: []
    - Agreements: []
      Image: resources/icons/service_logo.png
      Locale: en-US
      Name: Golang Runtime Environment
      ShortDescription: Golang is a statically typed, compiled programming language designed by Robert Griesemer, Rob Pike, and Ken Thompson of Google in 2007 and officially released in 2009. The goal of Go language design is to achieve efficient compilation, efficient execution, easy programming, and efficient data processing.
      Softwares: []
  ShareType: Public
  ApprovalType: Manual
Artifact: {}
